development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url:  postgres://bjxvotsmfssyyd:d33010b74f7ba048990167f30443aa5d2bf63a782693b436874b0504441ac70c@ec2-54-235-220-220.compute-1.amazonaws.com:5432/d28ums4mq4gehi
  channel_prefix: nameofapp_production
